version: '3.4'

services:
  orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6080:80"
      - "6443:443"

  productapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
      - "8443:443"


  userapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "7080:80"
      - "7443:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
